export const destinations = [
  {
    id: 1,
    name: 'Agra',
    location: 'Agra, Uttar Pradesh',
    category: 'Heritage',
    rating: 4.9,
    entryFee: 250,
    description: 'Home of the Taj Mahal — the timeless monument of love. Agra also boasts Agra Fort and Fatehpur Sikri, Mughal masterpieces along the Yamuna.',
    image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/3ace818a0_generated_image.png',
  },
  {
    id: 2,
    name: 'Kerala',
    location: 'Kochi, Kerala',
    category: 'Backwater',
    rating: 4.9,
    entryFee: 0,
    description: "God's Own Country — tranquil backwaters, lush tea plantations in Munnar, wildlife in Thekkady and the famous houseboats of Alleppey. A tropical marvel.",
    image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/c7340e5f3_generated_image.png',
  },
  {
    id: 3,
    name: 'Udaipur',
    location: 'Udaipur, Rajasthan',
    category: 'Heritage',
    rating: 4.8,
    entryFee: 100,
    description: 'The City of Lakes — romantic Udaipur shimmers with Lake Pichola, the grand City Palace and island palaces. A royal desert oasis.',
    image: 'https://images.unsplash.com/photo-1589901164570-f9de6556e1c1?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 4,
    name: 'Jaipur',
    location: 'Jaipur, Rajasthan',
    category: 'Heritage',
    rating: 4.8,
    entryFee: 100,
    description: 'The Pink City — a regal capital of grand palaces, mighty forts and bustling bazaars. Amber Fort, Hawa Mahal and City Palace showcase Rajput grandeur.',
    image: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 5,
    name: 'Manali',
    location: 'Manali, Himachal Pradesh',
    category: 'Hill Station',
    rating: 4.8,
    entryFee: 0,
    description: 'A Himalayan haven of snow-capped peaks, pine forests and adventure sports. Gateway to Rohtang Pass, Solang Valley and the mystical Old Manali.',
    image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/6cbb63b3c_generated_image.png',
  },
  {
    id: 6,
    name: 'Goa',
    location: 'Panaji, Goa',
    category: 'Beach',
    rating: 4.8,
    entryFee: 0,
    description: "India's sunshine state, famous for golden beaches, Portuguese heritage, seafood and a vibrant nightlife. From lively Baga to serene Palolem, Goa is a coastal paradise.",
    image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/4334f37da_generated_image.png',
  },
  {
    id: 7,
    name: 'Mysore',
    location: 'Mysore, Karnataka',
    category: 'Heritage',
    rating: 4.7,
    entryFee: 70,
    description: 'The City of Palaces — home to the magnificent Mysore Palace, Chamundi Hill and the sandalwood trade. Famous for its Dussehra festivities.',
    image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/c263f609b_generated_image.png',
  },
  {
    id: 8,
    name: 'Hyderabad',
    location: 'Hyderabad, Telangana',
    category: 'Metro',
    rating: 4.7,
    entryFee: 50,
    description: 'The City of Pearls and Nizams — where Mughal heritage meets modern tech. Famous for Charminar, biryani, Golconda Fort and Hussain Sagar Lake.',
    image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/c5498814c_generated_image.png',
  },
  {
    id: 9,
    name: 'Mumbai',
    location: 'Mumbai, Maharashtra',
    category: 'Metro',
    rating: 4.7,
    entryFee: 0,
    description: "The City of Dreams — India's vibrant financial and film capital. Gateway of India, Marine Drive, Elephanta Caves and the buzz of Bollywood.",
    image: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 10,
    name: 'Delhi',
    location: 'New Delhi, Delhi',
    category: 'Metro',
    rating: 4.8,
    entryFee: 50,
    description: "India's capital — a tapestry of Mughal monuments, colonial grandeur and modern bustle. Red Fort, India Gate, Qutub Minar and Chandni Chowk.",
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
  },
];

export const categories = ['All', 'Heritage', 'Backwater', 'Hill Station', 'Beach', 'Metro'];

export const attractions = [
  { id: 1, name: 'Taj Mahal', city: 'Agra', type: 'Heritage', description: 'The world’s greatest monument of love — a white marble mausoleum on the Yamuna.', image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=80' },
  { id: 2, name: 'Agra Fort', city: 'Agra', type: 'Historical', description: 'A monumental red sandstone fort and former Mughal royal residence.', image: 'https://images.unsplash.com/photo-1591018653367-9c01498b3320?auto=format&fit=crop&w=900&q=80' },
  { id: 3, name: 'Lake Pichola', city: 'Udaipur', type: 'Nature', description: 'The romantic heart of Udaipur — boat cruises pass palaces and the Aravalli hills.', image: 'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=900&q=80' },
  { id: 4, name: 'City Palace', city: 'Udaipur', type: 'Heritage', description: 'A lakeside royal complex with courtyards, galleries and views across the old city.', image: 'https://images.unsplash.com/photo-1589901164570-f9de6556e1c1?auto=format&fit=crop&w=900&q=80' },
  { id: 5, name: 'Amber Fort', city: 'Jaipur', type: 'Historical', description: 'A hilltop fort known for ornate halls, courtyards and sweeping valley views.', image: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=900&q=80' },
  { id: 6, name: 'Hawa Mahal', city: 'Jaipur', type: 'Heritage', description: 'Jaipur’s iconic Palace of Winds, famed for its honeycomb façade and jharokhas.', image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=900&q=80' },
  { id: 7, name: 'Mysore Palace', city: 'Mysore', type: 'Museum', description: 'A dazzling Indo-Saracenic palace and former seat of the Wodeyar dynasty.', image: 'https://media.base44.com/images/public/6aaaa90331fd628239671c09/c263f609b_generated_image.png' },
  { id: 8, name: 'Alleppey Backwaters', city: 'Kerala', type: 'Nature', description: 'Cruise serene palm-fringed backwaters on a traditional houseboat.', image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80' },
  { id: 9, name: 'Munnar Tea Gardens', city: 'Kerala', type: 'Nature', description: 'Rolling tea plantations and cool mountain air in the Western Ghats.', image: 'https://plus.unsplash.com/premium_photo-1697730314165-2cd71dc3a6a4?auto=format&fit=crop&w=900&q=80' },
  { id: 10, name: 'Periyar Wildlife Sanctuary', city: 'Kerala', type: 'Wildlife', description: 'A forest reserve known for lake-side wildlife watching and guided nature walks.', image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=80' },
  { id: 11, name: 'Solang Valley', city: 'Manali', type: 'Adventure', description: 'A mountain playground for paragliding, hiking and winter sports.', image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=900&q=80' },
  { id: 12, name: 'Hadimba Devi Temple', city: 'Manali', type: 'Temple', description: 'A peaceful cedar-forest shrine with distinctive timber architecture.', image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=900&q=80' },
  { id: 13, name: 'Palolem Beach', city: 'Goa', type: 'Beach', description: 'A palm-lined crescent of sand with calm water and sunset boat trips.', image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80' },
  { id: 14, name: 'Basilica of Bom Jesus', city: 'Goa', type: 'Historical', description: 'A celebrated Baroque church in Old Goa and a UNESCO World Heritage site.', image: 'https://images.unsplash.com/photo-1768728678060-598c3b983b3f?auto=format&fit=crop&w=900&q=80' },
  { id: 15, name: 'Charminar', city: 'Hyderabad', type: 'Heritage', description: 'The four-minaret landmark at the heart of Hyderabad’s historic bazaar district.', image: 'https://images.unsplash.com/photo-1741545979534-02f59c742730?auto=format&fit=crop&w=900&q=80' },
  { id: 16, name: 'Golconda Fort', city: 'Hyderabad', type: 'Historical', description: 'A dramatic hilltop fortress celebrated for its acoustics and panoramic views.', image: 'https://images.unsplash.com/photo-1662925725008-acceac88c39c?auto=format&fit=crop&w=900&q=80' },
  { id: 17, name: 'Gateway of India', city: 'Mumbai', type: 'Heritage', description: 'A waterfront monument overlooking the Arabian Sea and Mumbai Harbour.', image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=900&q=80' },
  { id: 18, name: 'Marine Drive', city: 'Mumbai', type: 'Nature', description: 'A sweeping seaside promenade known for evening walks and city lights.', image: 'https://images.unsplash.com/photo-1716396635935-b7ba3d91a1cb?auto=format&fit=crop&w=900&q=80' },
  { id: 19, name: 'Red Fort', city: 'Delhi', type: 'Historical', description: 'A landmark Mughal fort of red sandstone in the heart of Old Delhi.', image: 'https://images.unsplash.com/photo-1744979197022-f9f70e8a9402?auto=format&fit=crop&w=900&q=80' },
  { id: 20, name: 'Qutub Minar', city: 'Delhi', type: 'Heritage', description: 'A soaring medieval minaret surrounded by an atmospheric archaeological complex.', image: 'https://images.unsplash.com/photo-1748500192752-6f3f441c2a51?auto=format&fit=crop&w=900&q=80' },
];

export const hotels = [
  { id: 1, name: 'Taj Lake Palace', city: 'Udaipur', price: 42000, rating: 4.9, image: 'https://images.unsplash.com/photo-1718797054890-e58742729f2d?auto=format&fit=crop&w=900&q=80', description: 'Set on Jag Niwas island in Lake Pichola; guests reach the palace by boat from the City Palace jetty.' },
  { id: 2, name: 'The Oberoi Udaivilas', city: 'Udaipur', price: 38000, rating: 4.9, image: 'https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=900&q=80', description: 'A lakeside resort on the western bank of Lake Pichola, across the water from Udaipur’s old city.' },
  { id: 3, name: 'Rambagh Palace', city: 'Jaipur', price: 36000, rating: 4.8, image: 'https://images.unsplash.com/photo-1677129667171-92abd8740fa3?auto=format&fit=crop&w=900&q=80', description: 'A former royal residence on Bhawani Singh Road, close to Jaipur’s Central Park and the old city.' },
  { id: 4, name: 'Samode Haveli', city: 'Jaipur', price: 18000, rating: 4.7, image: 'https://images.unsplash.com/photo-1655516433028-9e0e1599cf8b?auto=format&fit=crop&w=900&q=80', description: 'A heritage haveli in Gangapole, inside Jaipur’s old walled city and a short drive from Hawa Mahal.' },
  { id: 5, name: 'The Oberoi Amarvilas', city: 'Agra', price: 32000, rating: 4.9, image: 'https://images.unsplash.com/photo-1678913308053-316cee77afe9?auto=format&fit=crop&w=900&q=80', description: 'On Taj East Gate Road, around 600 metres from the Taj Mahal’s east entrance.' },
  { id: 6, name: 'Kumarakom Lake Resort', city: 'Kerala', price: 14500, rating: 4.6, image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=900&q=80', description: 'A backwater resort in Kumarakom on Vembanad Lake, near the Kumarakom Bird Sanctuary.' },
  { id: 7, name: 'The Himalayan', city: 'Manali', price: 12000, rating: 4.7, image: 'https://images.unsplash.com/photo-1613744516210-fad1239fb6e0?auto=format&fit=crop&w=900&q=80', description: 'A mountain-style stay in Old Manali, near Hadimba Devi Temple and the cedar forest.' },
  { id: 8, name: 'Taj Exotica Resort & Spa', city: 'Goa', price: 22000, rating: 4.8, image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=900&q=80', description: 'A beachfront resort at Benaulim in South Goa, near Colva and the quiet village lanes.' },
  { id: 9, name: 'The Leela Palace New Delhi', city: 'Delhi', price: 25000, rating: 4.8, image: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=900&q=80', description: 'In the Diplomatic Enclave of Chanakyapuri, a convenient base for central New Delhi.' },
  { id: 10, name: 'Taj Mahal Palace', city: 'Mumbai', price: 28000, rating: 4.8, image: 'https://images.unsplash.com/photo-1742844552700-3926862c5311?auto=format&fit=crop&w=900&q=80', description: 'A landmark waterfront hotel at Apollo Bunder in Colaba, opposite the Gateway of India.' },
];

export const transportOptions = [
  { id: 1, mode: 'Flight', operator: 'IndiGo', from: 'Delhi', to: 'Udaipur', departure: '06:30', duration: '1h 20m', fare: 4200, availability: 'Available' },
  { id: 2, mode: 'Flight', operator: 'Air India', from: 'Mumbai', to: 'Jaipur', departure: '08:20', duration: '1h 55m', fare: 5100, availability: 'Limited' },
  { id: 3, mode: 'Train', operator: 'Mewar Express', from: 'Delhi', to: 'Udaipur', departure: '19:00', duration: '12h 35m', fare: 1450, availability: 'Available' },
  { id: 4, mode: 'Train', operator: 'Shatabdi Express', from: 'Delhi', to: 'Jaipur', departure: '06:10', duration: '4h 35m', fare: 980, availability: 'Available' },
  { id: 5, mode: 'Bus', operator: 'RSRTC Volvo', from: 'Jaipur', to: 'Udaipur', departure: '21:30', duration: '7h 10m', fare: 850, availability: 'Available' },
  { id: 6, mode: 'Flight', operator: 'IndiGo', from: 'Mumbai', to: 'Goa', departure: '10:15', duration: '1h 10m', fare: 3500, availability: 'Available' },
  { id: 7, mode: 'Train', operator: 'Konkan Express', from: 'Mumbai', to: 'Goa', departure: '11:40', duration: '10h 20m', fare: 720, availability: 'Limited' },
  { id: 8, mode: 'Bus', operator: 'KSRTC Airavat', from: 'Bengaluru', to: 'Mysore', departure: '09:00', duration: '3h 15m', fare: 540, availability: 'Available' },
  { id: 9, mode: 'Flight', operator: 'Air India', from: 'Delhi', to: 'Agra', departure: '07:25', duration: '1h 15m', fare: 3900, availability: 'Available' },
  { id: 10, mode: 'Train', operator: 'Kerala Express', from: 'Delhi', to: 'Kerala', departure: '11:25', duration: '38h 10m', fare: 2100, availability: 'Available' },
  { id: 11, mode: 'Flight', operator: 'IndiGo', from: 'Delhi', to: 'Manali', departure: '09:05', duration: '1h 30m', fare: 4800, availability: 'Limited' },
  { id: 12, mode: 'Taxi', operator: 'City Taxi', from: 'Jaipur', to: 'Amber Fort', departure: 'On demand', duration: '35m', fare: 650, availability: 'Available' },
  { id: 13, mode: 'Rental Car', operator: 'Zoomcar', from: 'Udaipur', to: 'Udaipur city', departure: 'On demand', duration: 'Flexible', fare: 2400, availability: 'Available' },
  { id: 14, mode: 'Bus', operator: 'HRTC Volvo', from: 'Delhi', to: 'Manali', departure: '18:00', duration: '12h 00m', fare: 1600, availability: 'Available' },
  { id: 15, mode: 'Flight', operator: 'IndiGo', from: 'Hyderabad', to: 'Mumbai', departure: '14:10', duration: '1h 25m', fare: 3200, availability: 'Available' },
  { id: 16, mode: 'Taxi', operator: 'Airport Transfer', from: 'Agra', to: 'Taj Mahal', departure: 'On demand', duration: '20m', fare: 450, availability: 'Available' },
];
