export const guides = [
  {
    id: 1,
    name: 'Vikram Singh',
    destination: 'Jaipur',
    rating: 4.9,
    description: 'A royal Rajasthan storyteller — forts, palaces and the secrets of the Pink City.',
    languages: ['English', 'Hindi', 'French'],
    experience: 15,
    rate: 2000,
    image: 'https://randomuser.me/api/portraits/men/68.jpg',
  },
  {
    id: 2,
    name: 'Thomas Varghese',
    destination: 'Kerala',
    rating: 4.8,
    description: 'Backwater and spice plantation expert who crafts authentic Kerala houseboat journeys.',
    languages: ['English', 'Hindi', 'Malayalam'],
    experience: 12,
    rate: 1800,
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
  },
  {
    id: 3,
    name: 'Karan Mewar',
    destination: 'Udaipur',
    rating: 4.8,
    description: "Udaipur's lake-and-palace connoisseur with a flair for romantic sunset tours.",
    languages: ['English', 'Hindi', 'Italian'],
    experience: 13,
    rate: 1900,
    image: 'https://randomuser.me/api/portraits/men/75.jpg',
  },
  {
    id: 4,
    name: 'Priya Desai',
    destination: 'Mumbai',
    rating: 4.7,
    description: 'Mumbai city and Bollywood expert — heritage walks, markets and film city tours.',
    languages: ['English', 'Hindi', 'Marathi'],
    experience: 10,
    rate: 1500,
    image: 'https://randomuser.me/api/portraits/women/32.jpg',
  },
  {
    id: 5,
    name: 'Ravi Naik',
    destination: 'Goa',
    rating: 4.7,
    description: 'A passionate Goan guide specializing in beaches, Portuguese churches and hidden waterfalls.',
    languages: ['English', 'Hindi', 'Konkani'],
    experience: 8,
    rate: 1500,
    image: 'https://randomuser.me/api/portraits/men/44.jpg',
  },
  {
    id: 6,
    name: 'Imran Khan',
    destination: 'Agra',
    rating: 4.7,
    description: 'Mughal history specialist who brings the Taj Mahal and Agra Fort to life.',
    languages: ['English', 'Hindi', 'Urdu', 'Spanish'],
    experience: 10,
    rate: 1200,
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 7,
    name: 'Ankit Thakur',
    destination: 'Manali',
    rating: 4.7,
    description: 'Adventure guide for trekking, skiing and offbeat Himalayan trails around Manali.',
    languages: ['English', 'Hindi'],
    experience: 7,
    rate: 1600,
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: 8,
    name: 'Rahul Sharma',
    destination: 'Delhi',
    rating: 4.7,
    description: 'Old Delhi and Mughal monuments specialist — from Red Fort to street food walks.',
    languages: ['English', 'Hindi', 'German'],
    experience: 14,
    rate: 1700,
    image: 'https://randomuser.me/api/portraits/men/12.jpg',
  },
  {
    id: 9,
    name: 'Suresh Reddy',
    destination: 'Hyderabad',
    rating: 4.6,
    description: 'Nizam heritage and biryani trail expert — Charminar to Golconda and beyond.',
    languages: ['English', 'Hindi', 'Telugu'],
    experience: 9,
    rate: 1400,
    image: 'https://randomuser.me/api/portraits/men/21.jpg',
  },
  {
    id: 10,
    name: 'Deepak Rao',
    destination: 'Mysore',
    rating: 4.6,
    description: "Palace and silk expert — Mysore's royal history, markets and Dussehra traditions.",
    languages: ['English', 'Hindi', 'Kannada'],
    experience: 11,
    rate: 1300,
    image: 'https://randomuser.me/api/portraits/men/90.jpg',
  },
];
